name: Build .NET Desktop

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Build
      run: dotnet build src --configuration Release
      
    - name: Publish
      run: dotnet publish -r win-x64 --self-contained=false /p:PublishSingleFile=true src\dotnet-build-demo.csproj -o publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build-demo.exe.zip
        path: D:\a\dotnet-build-demo\dotnet-build-demo\publish\dotnet-build-demo.exe
        retention-days: 90
